<?php /* Template Name: AboutUs Template */ ?>
<!-- Page Content -->
<a  name="services"></a>
<div class="banner2">

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Brothers</h2>
                <h3>We will never be typical, because the world deserves better.</h3>
            </div>
        </div>
    </div>
    <!-- /.container -->

</div>
<!-- /.banner -->

<!-- #region Jssor Slider Begin -->

<!-- Generated by Jssor Slider Maker. -->
<!-- This demo works with jquery library -->    
<script type="text/javascript" src="<?php bloginfo('template_url'); ?>/brothersSlider/js/jssor.slider.mini.js"></script>
<!-- use jssor.slider.debug.js instead for debug -->
<script>
    jQuery(document).ready(function ($) {

        var jssor_1_options = {
            $AutoPlay: false,
            $AutoPlaySteps: 4,
            $SlideDuration: 160,
            $SlideWidth: 250,
            $SlideHeight: 350,
            $SlideSpacing: 3,
            $Cols: 5,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$,
                $Steps: 4
            },
            $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $SpacingX: 1,
                $SpacingY: 1
            }
        };

        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

        //responsive code begin
        //you can remove responsive code if you don't want the slider scales while window resizing
        function ScaleSlider() {
            var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
            if (refSize) {
                refSize = Math.min(refSize, 809);
                jssor_1_slider.$ScaleWidth(refSize);
            }
            else {
                window.setTimeout(ScaleSlider, 30);
            }
        }
        ScaleSlider();
        $(window).bind("load", ScaleSlider);
        $(window).bind("resize", ScaleSlider);
        $(window).bind("orientationchange", ScaleSlider);
        //responsive code end
    });
</script>

<style>

    /* jssor slider bullet navigator skin 03 css */
    /*
    .jssorb03 div           (normal)
    .jssorb03 div:hover     (normal mouseover)
    .jssorb03 .av           (active)
    .jssorb03 .av:hover     (active mouseover)
    .jssorb03 .dn           (mousedown)


*/
    .brotherImage{
        text-align: center;
    }
    .jssorb03 {
        position: absolute;
    }
    .jssorb03 div, .jssorb03 div:hover, .jssorb03 .av {
        position: absolute;
        /* size of bullet elment */
        width: 21px;
        height: 21px;
        text-align: center;
        line-height: 21px;
        color: white;
        font-size: 12px;
        background: url('<?php bloginfo('template_url'); ?>/brothersSlider/img/b03.png') no-repeat;
        overflow: hidden;
        cursor: pointer;
    }
    .jssorb03 div { background-position: -5px -4px; }
    .jssorb03 div:hover, .jssorb03 .av:hover { background-position: -35px -4px; }
    .jssorb03 .av { background-position: -65px -4px; }
    .jssorb03 .dn, .jssorb03 .dn:hover { background-position: -95px -4px; }

    /* jssor slider arrow navigator skin 03 css */
    /*
    .jssora03l                  (normal)
    .jssora03r                  (normal)
    .jssora03l:hover            (normal mouseover)
    .jssora03r:hover            (normal mouseover)
    .jssora03l.jssora03ldn      (mousedown)
    .jssora03r.jssora03rdn      (mousedown)
    */
    .jssora03l, .jssora03r {
        display: block;
        position: absolute;
        /* size of arrow element */
        width: 55px;
        height: 55px;
        cursor: pointer;
        background: url('<?php bloginfo('template_url'); ?>/brothersSlider/img/a03.png') no-repeat;
        overflow: hidden;
    }
    .jssora03l { background-position: -3px -33px; }
    .jssora03r { background-position: -63px -33px; }
    .jssora03l:hover { background-position: -123px -33px; }
    .jssora03r:hover { background-position: -183px -33px; }
    .jssora03l.jssora03ldn { background-position: -243px -33px; }
    .jssora03r.jssora03rdn { background-position: -303px -33px; }
</style>

<?php
//Gather brothers information
$brotherArray = array();
$brotherListPath = get_bloginfo('template_url') . "/brothersSlider/deltasig-rx.csv";
$row = 1;
try
{

    if (($handle = fopen($brotherListPath, "r")) !== FALSE) {

        while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
            if($row != 1 && strtolower($data[1]) != "nickname")
            {
                $num = count($data);
                $brotherSingleHTML = "";
                $nameFormatted = "";
                $brotherFirstName = "";
                $brotherLastName = "";
                if (strpos($data[1], '.') !== false || strpos($data[1], '@') !== false) {
                    $nameFormatted = str_replace(str_split('@.'), ' ', $data[1]);
                    $nameFormatted = preg_replace('/[0-9]+/', '', $nameFormatted);


                }
                else {
                    $nameFormatted = $data[1];
                }

                $nameSplit = explode(' ', $nameFormatted);
                $ct = 0;
                foreach ($nameSplit as $ns) {
                    $nameSplit[$ct] = ucfirst($ns);
                    $ct++;
                }
                $brotherFirstName = $nameSplit[0];
                $brotherLastName = $nameSplit[1];
                $brotherID = strtolower($brotherFirstName . "_" . $brotherLastName);

                $brotherSingleHTML = '<div id="'. $brotherID . '" class="brotherImage" style="display: none;">
                    <img data-u="image" src="' . get_bloginfo('template_url') . '/brothersSlider/img/placeholder.png" />
                    <h3>' . $brotherFirstName . " " . $brotherLastName . '</h3>
                </div>';

                $brotherArray[$brotherID] = $brotherSingleHTML;

            }
            $row++;
        }
        fclose($handle);

        ksort($brotherArray);
    }

}
catch(Exception $e)
{
    var_dump($e);
}


?>



<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1000px; height: 396px; overflow: hidden; visibility: hidden;">
    <!-- Loading Screen -->
    <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
        <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
        <div style="position:absolute;display:block;background:url('<?php bloginfo('template_url'); ?>/brothersSlider/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
    </div>
    <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 1000px; height: 396px; overflow: hidden;">
        <?php
            foreach($brotherArray as $brother)
            {
                echo $brother;
            }
        ?>
        <a data-u="ad" href="http://www.jssor.com" style="display:none">jQuery Slider</a>

    </div>
    <!-- Bullet Navigator
    <div data-u="navigator" class="jssorb03" style="bottom:10px;right:10px;">

        <div data-u="prototype" style="width:21px;height:21px;">
            <div data-u="numbertemplate"></div>
        </div>
    </div>
    Arrow Navigator -->
    <span data-u="arrowleft" class="jssora03l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
    <span data-u="arrowright" class="jssora03r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
</div>

<!-- #endregion Jssor Slider End -->

